steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['install']

  # Build with environment variables
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['build']
    env:
      - 'VITE_APP_URL=https://orchestralabs.org/'
      - 'VITE_WALLETCONNECT_PROJECT_ID=70ba37949838afd24f17421f5b6bcfd0'

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--no-promote']

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
