steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--build-arg=VITE_APP_URL=https://orchestralabs.org/'
      - '--build-arg=VITE_WALLETCONNECT_PROJECT_ID=70ba37949838afd24f17421f5b6bcfd0'
      - '-t'
      - 'gcr.io/$PROJECT_ID/symphony-site'
      - '.'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
