steps:
  # Create .env file for App Engine build
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "VITE_APP_URL=https://orchestralabs.org/" > .env && echo "VITE_WALLETCONNECT_PROJECT_ID=70ba37949838afd24f17421f5b6bcfd0" >> .env && cat .env'

  # Deploy to App Engine (it will run yarn install && yarn build with .env)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
