FROM node:20.9.0
WORKDIR /usr/src/app

COPY . .

ENV PORT=4173
EXPOSE 4173

# Build arguments for Vite (baked in at build time)
ARG VITE_APP_URL=https://orchestralabs.org/
ARG VITE_WALLETCONNECT_PROJECT_ID
ENV VITE_APP_URL=$VITE_APP_URL
ENV VITE_WALLETCONNECT_PROJECT_ID=$VITE_WALLETCONNECT_PROJECT_ID

ENV YARN_ENABLE_IMMUTABLE_INSTALLS=false
RUN yarn install
RUN yarn build

CMD ["yarn", "start"]
